/**
 * Zuno Authentication
 * - First screen is always Login / Create Account when there is no session.
 * - Login by ID or email.
 * - New IDs are generated by Supabase from 1000 upward.
 * - Invitation ID is mandatory.
 * - Keeps legacy user field names so the current UI/store/rooms keep working.
 */
class AuthManager {
  constructor() {
    this.currentUser = null;
    this.users = [];
    this.ready = this.boot();
  }

  get client() {
    return window.supabaseService?.client || null;
  }

  async boot() {
    this.applyZunoBranding();
    this.injectResponsiveStyles();
    this.installAuthGate();

    if (!this.client) {
      this.lockApp();
      this.showGate('login');
      this.setGateMessage('اربط Supabase أولاً من إعدادات الربط.', 'error');
      return;
    }

    const { data } = await this.client.auth.getSession();
    if (data?.session?.user) {
      await this.loadProfile(data.session.user);
      this.unlockApp();
      this.hideGate();
    } else {
      this.lockApp();
      this.showGate('login');
    }

    this.client.auth.onAuthStateChange(async (event, session) => {
      if (session?.user) {
        await this.loadProfile(session.user);
        this.unlockApp();
        this.hideGate();
        this.refreshUI();
      } else if (event === 'SIGNED_OUT') {
        this.currentUser = null;
        this.lockApp();
        this.showGate('login');
      }
    });
  }

  applyZunoBranding() {
    document.title = 'Zuno';

    const run = () => {
      // Header brand
      document.querySelectorAll('.font-cyber').forEach(el => {
        if ((el.textContent || '').trim().toUpperCase() === 'ZELZAL') {
          el.textContent = 'Zuno';
        }
      });

      // Hide the old Arabic subtitle beside the logo and keep the name only.
      document.querySelectorAll('header span').forEach(el => {
        const t = (el.textContent || '').trim();
        if (t === 'زلزال نيون') el.style.display = 'none';
      });

      document.querySelectorAll('header div').forEach(el => {
        if ((el.textContent || '').trim() === 'Cyber Platform 2.0') {
          el.style.display = 'none';
        }
      });

      // Rename visible announcements without touching user content.
      const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
      const nodes = [];
      while (walker.nextNode()) nodes.push(walker.currentNode);
      nodes.forEach(node => {
        if (!node.parentElement) return;
        if (['SCRIPT','STYLE','TEXTAREA','INPUT'].includes(node.parentElement.tagName)) return;
        node.nodeValue = node.nodeValue
          .replace(/ZELZAL/g, 'Zuno')
          .replace(/Zelzal/g, 'Zuno')
          .replace(/زلزال نيون/g, 'Zuno')
          .replace(/منصة زلزال/g, 'Zuno')
          .replace(/إعلان زلزال/g, 'إعلان Zuno');
      });
    };

    if (document.readyState === 'loading') {
      document.addEventListener('DOMContentLoaded', run, { once: true });
    } else {
      run();
    }
  }

  injectResponsiveStyles() {
    const style = document.createElement('style');
    style.id = 'zuno-auth-ui-style';
    style.textContent = `
      html, body { width:100%; max-width:100%; overflow-x:hidden; }
      body.zuno-auth-locked > header,
      body.zuno-auth-locked > #main-app-shell { visibility:hidden !important; }

      #zuno-auth-gate {
        position:fixed; inset:0; z-index:999999;
        display:flex; align-items:center; justify-content:center;
        padding:20px;
        background:
          radial-gradient(circle at 50% 18%, rgba(65,90,255,.20), transparent 32%),
          radial-gradient(circle at 72% 55%, rgba(211,64,255,.10), transparent 35%),
          #040815;
        color:#fff; direction:rtl;
        overflow:auto;
      }
      #zuno-auth-gate.zuno-hidden { display:none !important; }
      .zuno-auth-card {
        width:min(100%, 440px);
        border:1px solid rgba(77,151,255,.28);
        border-radius:30px;
        padding:30px 22px;
        background:linear-gradient(180deg,rgba(9,16,42,.96),rgba(4,8,22,.98));
        box-shadow:0 25px 80px rgba(0,0,0,.55), 0 0 50px rgba(80,70,255,.08);
      }
      .zuno-logo {
        font-size:clamp(58px,18vw,88px);
        line-height:1;
        font-weight:900;
        letter-spacing:-4px;
        text-align:center;
        margin:24px 0 42px;
        background:linear-gradient(90deg,#22b8ff,#7267ff,#ec55ff);
        -webkit-background-clip:text;
        background-clip:text;
        color:transparent;
        filter:drop-shadow(0 0 18px rgba(100,92,255,.35));
      }
      .zuno-auth-tabs {
        display:grid; grid-template-columns:1fr 1fr;
        padding:5px; gap:5px;
        border-radius:17px;
        background:rgba(10,18,43,.88);
        margin-bottom:22px;
      }
      .zuno-auth-tab {
        border:0; border-radius:13px; padding:13px 8px;
        font-weight:800; color:#aeb8d4; background:transparent; cursor:pointer;
      }
      .zuno-auth-tab.active {
        color:#dff9ff;
        background:linear-gradient(90deg,rgba(18,153,210,.55),rgba(108,66,223,.55));
        box-shadow:0 0 20px rgba(35,167,255,.10);
      }
      .zuno-form { display:grid; gap:13px; }
      .zuno-form.hidden { display:none !important; }
      .zuno-field {
        width:100%; box-sizing:border-box;
        border:1px solid rgba(102,126,190,.26);
        background:rgba(7,13,33,.9);
        color:white; border-radius:15px;
        padding:15px 16px; outline:none;
        font-size:15px;
      }
      .zuno-field:focus {
        border-color:#21c6ff;
        box-shadow:0 0 0 3px rgba(33,198,255,.08);
      }
      .zuno-submit {
        margin-top:5px;
        border:0; border-radius:16px; padding:15px 18px;
        font-weight:900; font-size:17px; color:white; cursor:pointer;
        background:linear-gradient(90deg,#138cff,#7056f5,#d84cf0);
        box-shadow:0 12px 35px rgba(78,79,255,.28);
      }
      .zuno-submit:disabled { opacity:.55; cursor:wait; }
      .zuno-auth-msg {
        min-height:22px; margin-top:14px; text-align:center;
        font-size:13px; font-weight:700;
      }
      .zuno-auth-msg.error { color:#fb7185; }
      .zuno-auth-msg.success { color:#34d399; }

      @media (max-width: 640px) {
        header > div, #main-app-shell, #app-viewport { max-width:100% !important; width:100% !important; }
        #app-viewport { padding-left:12px !important; padding-right:12px !important; }
        .cyber-card { max-width:100% !important; box-sizing:border-box; }
        .zuno-auth-card { border-radius:24px; padding:26px 18px; }
      }
    `;
    document.head.appendChild(style);
  }

  installAuthGate() {
    const create = () => {
      let gate = document.getElementById('zuno-auth-gate');
      if (gate) return gate;

      gate = document.createElement('div');
      gate.id = 'zuno-auth-gate';
      gate.innerHTML = `
        <div class="zuno-auth-card">
          <div class="zuno-logo">Zuno</div>

          <div class="zuno-auth-tabs">
            <button type="button" id="zuno-tab-login" class="zuno-auth-tab active">تسجيل الدخول</button>
            <button type="button" id="zuno-tab-register" class="zuno-auth-tab">إنشاء حساب</button>
          </div>

          <form id="zuno-login-form" class="zuno-form">
            <input id="zuno-login-ident" class="zuno-field" required
                   placeholder="ID أو البريد الإلكتروني" autocomplete="username">
            <input id="zuno-login-pass" class="zuno-field" type="password" required
                   placeholder="كلمة المرور" autocomplete="current-password">
            <button class="zuno-submit" type="submit">تسجيل الدخول</button>
          </form>

          <form id="zuno-register-form" class="zuno-form hidden">
            <input id="zuno-reg-name" class="zuno-field" required placeholder="الاسم">
            <input id="zuno-reg-email" class="zuno-field" type="email" required placeholder="البريد الإلكتروني">
            <input id="zuno-reg-pass" class="zuno-field" type="password" required minlength="6" placeholder="كلمة المرور">
            <input id="zuno-reg-confirm" class="zuno-field" type="password" required minlength="6" placeholder="تأكيد كلمة المرور">
            <input id="zuno-reg-invite" class="zuno-field" inputmode="numeric" required placeholder="ID الدعوة - إجباري">
            <button class="zuno-submit" type="submit">إنشاء</button>
          </form>

          <div id="zuno-auth-msg" class="zuno-auth-msg"></div>
        </div>
      `;
      document.body.appendChild(gate);

      document.getElementById('zuno-tab-login').addEventListener('click', () => this.showGate('login'));
      document.getElementById('zuno-tab-register').addEventListener('click', () => this.showGate('register'));

      document.getElementById('zuno-login-form').addEventListener('submit', async (e) => {
        e.preventDefault();
        const btn = e.currentTarget.querySelector('button[type="submit"]');
        btn.disabled = true;
        this.setGateMessage('');
        try {
          await this.login({
            identifier: document.getElementById('zuno-login-ident').value,
            password: document.getElementById('zuno-login-pass').value
          });
          this.setGateMessage('تم تسجيل الدخول بنجاح', 'success');
          this.unlockApp();
          this.hideGate();
          this.refreshUI();
        } catch (err) {
          this.setGateMessage(err.message || 'تعذر تسجيل الدخول', 'error');
        } finally {
          btn.disabled = false;
        }
      });

      document.getElementById('zuno-register-form').addEventListener('submit', async (e) => {
        e.preventDefault();
        const btn = e.currentTarget.querySelector('button[type="submit"]');
        btn.disabled = true;
        this.setGateMessage('');
        try {
          await this.register({
            name: document.getElementById('zuno-reg-name').value,
            email: document.getElementById('zuno-reg-email').value,
            password: document.getElementById('zuno-reg-pass').value,
            confirmPassword: document.getElementById('zuno-reg-confirm').value,
            inviteId: document.getElementById('zuno-reg-invite').value
          });
          this.setGateMessage('تم إنشاء الحساب بنجاح', 'success');
          if (this.currentUser) {
            this.unlockApp();
            this.hideGate();
            this.refreshUI();
          } else {
            this.showGate('login');
            this.setGateMessage('تم إنشاء الحساب. سجّل الدخول بعد تأكيد البريد إن كان التأكيد مفعلاً.', 'success');
          }
        } catch (err) {
          this.setGateMessage(err.message || 'تعذر إنشاء الحساب', 'error');
        } finally {
          btn.disabled = false;
        }
      });

      return gate;
    };

    if (document.readyState === 'loading') {
      document.addEventListener('DOMContentLoaded', create, { once:true });
    } else {
      create();
    }
  }

  setGateMessage(text, type='') {
    const el = document.getElementById('zuno-auth-msg');
    if (!el) return;
    el.textContent = text || '';
    el.className = 'zuno-auth-msg' + (type ? ' ' + type : '');
  }

  showGate(mode='login') {
    const gate = document.getElementById('zuno-auth-gate');
    if (!gate) return;

    gate.classList.remove('zuno-hidden');

    const loginForm = document.getElementById('zuno-login-form');
    const registerForm = document.getElementById('zuno-register-form');
    const loginTab = document.getElementById('zuno-tab-login');
    const registerTab = document.getElementById('zuno-tab-register');

    const isLogin = mode !== 'register';
    loginForm?.classList.toggle('hidden', !isLogin);
    registerForm?.classList.toggle('hidden', isLogin);
    loginTab?.classList.toggle('active', isLogin);
    registerTab?.classList.toggle('active', !isLogin);
  }

  hideGate() {
    document.getElementById('zuno-auth-gate')?.classList.add('zuno-hidden');
    document.getElementById('auth-modal')?.classList.add('hidden');
  }

  lockApp() {
    document.body.classList.add('zuno-auth-locked');
  }

  unlockApp() {
    document.body.classList.remove('zuno-auth-locked');
  }

  async register({ name, email, password, confirmPassword, inviteId }) {
    if (!this.client) throw new Error('Supabase غير مربوط');
    if (!name?.trim() || !email?.trim() || !password || !inviteId?.toString().trim()) {
      throw new Error('يرجى ملء جميع الحقول');
    }
    if (password !== confirmPassword) throw new Error('كلمتا المرور غير متطابقتين');
    if (password.length < 6) throw new Error('كلمة المرور يجب أن تكون 6 أحرف على الأقل');

    const numericInvite = Number(String(inviteId).replace(/\D/g, ''));
    if (!Number.isInteger(numericInvite) || numericInvite < 1) {
      throw new Error('ID الدعوة غير صحيح');
    }

    // Optional quick check. The database trigger also checks it securely.
    const { data: inviteOk, error: inviteErr } = await this.client.rpc('zuno_invite_exists', {
      p_invite_id: numericInvite
    });
    if (inviteErr) throw new Error('تعذر التحقق من ID الدعوة');
    if (!inviteOk) throw new Error('ID الدعوة غير موجود');

    const { data, error } = await this.client.auth.signUp({
      email: email.trim().toLowerCase(),
      password,
      options: {
        data: {
          display_name: name.trim(),
          invite_id: numericInvite
        }
      }
    });

    if (error) throw new Error(this.translateAuthError(error.message));

    if (data?.session?.user) {
      await this.loadProfile(data.session.user);
    }
    return this.currentUser;
  }

  async login({ identifier, password }) {
    if (!this.client) throw new Error('Supabase غير مربوط');
    if (!identifier?.trim() || !password) throw new Error('أدخل ID أو البريد الإلكتروني وكلمة المرور');

    const ident = identifier.trim();
    let session = null;

    if (ident.includes('@')) {
      const { data, error } = await this.client.auth.signInWithPassword({
        email: ident.toLowerCase(),
        password
      });
      if (error) throw new Error('ID أو البريد أو كلمة المرور غير صحيحة');
      session = data.session;
    } else {
      const numericId = Number(ident.replace(/\D/g, ''));
      if (!Number.isInteger(numericId)) throw new Error('ID غير صحيح');

      const { data, error } = await this.client.functions.invoke('auth-login', {
        body: { identifier: numericId, password }
      });
      if (error) throw new Error('تعذر الاتصال بخدمة تسجيل الدخول');
      if (!data?.access_token || !data?.refresh_token) {
        throw new Error(data?.error || 'ID أو كلمة المرور غير صحيحة');
      }

      const { data: sessionData, error: sessionErr } = await this.client.auth.setSession({
        access_token: data.access_token,
        refresh_token: data.refresh_token
      });
      if (sessionErr) throw new Error('تعذر فتح الجلسة');
      session = sessionData.session;
    }

    if (!session?.user) throw new Error('تعذر تسجيل الدخول');
    await this.loadProfile(session.user);
    return this.currentUser;
  }

  async loadProfile(authUser) {
    if (!authUser || !this.client) return null;

    const { data: profile, error } = await this.client
      .from('profiles')
      .select('id,public_id,display_name,avatar_url,points,role,inviter_public_id,butterfly_last_claim,butterfly_spin_until,created_at')
      .eq('id', authUser.id)
      .single();

    if (error || !profile) {
      console.error('Profile load error:', error);
      throw new Error('تعذر تحميل بيانات الحساب');
    }

    const compat = this.getCompatState(authUser.id);

    this.currentUser = {
      id: authUser.id,
      customId: String(profile.public_id),
      publicId: profile.public_id,
      name: profile.display_name || 'مستخدم Zuno',
      email: authUser.email || '',
      phone: '',
      password: '',
      avatar: profile.avatar_url || this.defaultAvatar(),
      points: Number(profile.points || 0),
      role: profile.role || 'user',
      inviterId: profile.inviter_public_id,
      createdAt: profile.created_at,
      butterflyLastClaim: profile.butterfly_last_claim,
      butterflySpinActiveUntil: profile.butterfly_spin_until,
      countersOwned: compat.countersOwned || [],
      roomsOwned: compat.roomsOwned || [],
      energy: 100
    };

    this.users = [this.currentUser];
    this.saveCompatState();
    return this.currentUser;
  }

  getCompatState(userId) {
    try {
      return JSON.parse(localStorage.getItem('zuno_compat_' + userId) || '{}');
    } catch (_) {
      return {};
    }
  }

  saveCompatState() {
    if (!this.currentUser) return;
    const payload = {
      countersOwned: this.currentUser.countersOwned || [],
      roomsOwned: this.currentUser.roomsOwned || []
    };
    localStorage.setItem('zuno_compat_' + this.currentUser.id, JSON.stringify(payload));
  }

  saveUsers() {
    if (!this.currentUser) return;
    this.saveCompatState();

    if (this.client) {
      this.client.from('profiles').update({
        points: this.currentUser.points || 0,
        butterfly_last_claim: this.currentUser.butterflyLastClaim || null,
        butterfly_spin_until: this.currentUser.butterflySpinActiveUntil || null
      }).eq('id', this.currentUser.id).then(({error}) => {
        if (error) console.error('Profile sync error:', error);
      });
    }
  }

  async logout() {
    if (this.client) await this.client.auth.signOut();
    this.currentUser = null;
    this.lockApp();
    this.showGate('login');
  }

  updateProfile({ name, email, phone, password, avatar }) {
    if (!this.currentUser || !this.client) throw new Error('لا يوجد مستخدم مسجل');

    const oldEmail = this.currentUser.email;

    if (name?.trim()) this.currentUser.name = name.trim();
    if (avatar?.trim()) this.currentUser.avatar = avatar.trim();

    // Keep UI responsive, then sync in background.
    this.client.from('profiles').update({
      display_name: this.currentUser.name,
      avatar_url: this.currentUser.avatar
    }).eq('id', this.currentUser.id).then(({error}) => {
      if (error) window.zelzalApp?.showNotification('تعذر حفظ الاسم أو الصورة', 'error');
    });

    const authUpdates = {};
    if (email?.trim() && email.trim().toLowerCase() !== oldEmail.toLowerCase()) {
      authUpdates.email = email.trim().toLowerCase();
      this.currentUser.email = authUpdates.email;
    }
    if (password?.trim()) {
      if (password.trim().length < 6) throw new Error('كلمة المرور يجب أن تكون 6 أحرف على الأقل');
      authUpdates.password = password.trim();
    }
    if (Object.keys(authUpdates).length) {
      this.client.auth.updateUser(authUpdates).then(({error}) => {
        if (error) window.zelzalApp?.showNotification(this.translateAuthError(error.message), 'error');
      });
    }

    return this.currentUser;
  }

  modifyPoints(delta, reason='نظام') {
    if (!this.currentUser) return false;
    const next = Number(this.currentUser.points || 0) + Number(delta || 0);
    if (next < 0) return false;

    this.currentUser.points = next;
    this.saveUsers();

    const transactions = window.supabaseService.getLocal('transactions', []);
    transactions.unshift({
      id:'tx_' + Date.now(),
      userId:this.currentUser.id,
      delta:Number(delta),
      reason,
      totalAfter:next,
      createdAt:new Date().toISOString()
    });
    window.supabaseService.setLocal('transactions', transactions.slice(0, 100));
    window.zelzalApp?.updateWalletDisplay();
    return true;
  }

  async refreshFromCloud() {
    const { data } = await this.client.auth.getUser();
    if (data?.user) await this.loadProfile(data.user);
    this.refreshUI();
  }

  refreshUI() {
    setTimeout(() => {
      window.zelzalApp?.updateWalletDisplay?.();
      window.zelzalApp?.renderAccountTab?.();

      const idEl = document.getElementById('profile-id-display');
      if (idEl && this.currentUser) idEl.textContent = this.currentUser.customId;

      const nameEl = document.getElementById('profile-name-display');
      if (nameEl && this.currentUser?.role === 'developer') {
        nameEl.innerHTML = `${this.escapeHtml(this.currentUser.name)} <span style="font-size:11px;color:#22d3ee">المطور</span>`;
      }
    }, 0);
  }

  defaultAvatar() {
    return 'https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Zuno';
  }

  translateAuthError(msg='') {
    const m = msg.toLowerCase();
    if (m.includes('already registered') || m.includes('already been registered')) return 'البريد الإلكتروني مستخدم بالفعل';
    if (m.includes('invalid login credentials')) return 'البريد أو كلمة المرور غير صحيحة';
    if (m.includes('password')) return 'كلمة المرور غير مقبولة';
    return msg || 'حدث خطأ في المصادقة';
  }

  escapeHtml(v='') {
    return String(v).replace(/[&<>"']/g, c => ({
      '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'
    }[c]));
  }

  // Kept only for compatibility with old buttons. Users cannot choose their own ID anymore.
  generateUniqueId() {
    return 'يُنشأ تلقائياً';
  }

  initDemoUserIfEmpty() {
    // Demo/guest accounts are intentionally disabled in Zuno.
    this.showGate('login');
  }
}

window.authManager = new AuthManager();
