-- =========================================================
-- ZONO V1 — Update 07
-- شراء نفس الطائر أكثر من مرة + جمع الإنتاج اليومي
-- شغّل هذا الملف مرة واحدة داخل Supabase > SQL Editor
-- =========================================================

begin;

-- كل عملية شراء لها مدة 500 يوم مستقلة.
create table if not exists public.bird_purchases (
    id bigint generated by default as identity primary key,
    user_id uuid not null references public.profiles(id) on delete cascade,
    item_id text not null,
    purchase_price bigint not null check (purchase_price >= 0),
    daily_seeds bigint not null check (daily_seeds >= 0),
    purchased_at timestamptz not null default now(),
    ends_at timestamptz not null,
    last_claim_at timestamptz not null default now()
);

create index if not exists bird_purchases_user_idx
    on public.bird_purchases(user_id);

create index if not exists bird_purchases_user_active_idx
    on public.bird_purchases(user_id, ends_at);

alter table public.bird_purchases enable row level security;

drop policy if exists "own bird purchases read" on public.bird_purchases;
create policy "own bird purchases read"
on public.bird_purchases
for select
to authenticated
using (user_id = auth.uid());

revoke insert, update, delete on public.bird_purchases from anon, authenticated;
grant select on public.bird_purchases to authenticated;

-- تحويل الطيور المملوكة القديمة إلى عملية شراء واحدة إن لم تكن مسجلة.
insert into public.bird_purchases(
    user_id, item_id, purchase_price, daily_seeds,
    purchased_at, ends_at, last_claim_at
)
select
    bi.user_id,
    bi.item_id,
    coalesce(public.zono_bird_price(bi.item_id), 0),
    coalesce(public.zono_bird_daily_seeds(bi.item_id), 0),
    bi.purchased_at,
    bi.purchased_at + interval '500 days',
    bi.purchased_at
from public.bird_inventory bi
where bi.item_id <> 'classic_gold'
  and coalesce(public.zono_bird_daily_seeds(bi.item_id), 0) > 0
  and not exists (
      select 1
      from public.bird_purchases bp
      where bp.user_id = bi.user_id
        and bp.item_id = bi.item_id
  );

-- عدد مرات شراء كل نوع.
create or replace function public.zono_bird_purchase_counts()
returns table(
    item_id text,
    purchase_count bigint,
    daily_total bigint
)
language sql
security definer
set search_path = public
as $$
    select
        bp.item_id,
        count(*)::bigint as purchase_count,
        coalesce(sum(
            case when bp.ends_at >= now() then bp.daily_seeds else 0 end
        ), 0)::bigint as daily_total
    from public.bird_purchases bp
    where bp.user_id = auth.uid()
    group by bp.item_id
    order by min(bp.purchased_at);
$$;

-- مجموع ما يتحصل عليه المستخدم يومياً.
create or replace function public.zono_bird_daily_totals()
returns jsonb
language sql
security definer
set search_path = public
as $$
    select jsonb_build_object(
        'seeds_daily',
        coalesce((
            select sum(bp.daily_seeds)
            from public.bird_purchases bp
            where bp.user_id = auth.uid()
              and bp.ends_at >= now()
        ), 0),
        'feathers_daily', 60,
        'active_purchases',
        coalesce((
            select count(*)
            from public.bird_purchases bp
            where bp.user_id = auth.uid()
              and bp.ends_at >= now()
        ), 0)
    );
$$;

-- شراء الطائر بالبذور.
-- نفس الطائر الحالي يمكن شراؤه عدة مرات بنفس السعر.
-- الطيور الأقدم من الشكل الحالي تبقى مقفلة ولا يمكن الرجوع إليها.
create or replace function public.zono_buy_bird(p_item_id text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_price bigint;
    v_new_rank integer;
    v_current_rank integer;
    v_balance bigint;
    v_daily bigint;
    v_count bigint;
    v_total_daily bigint;
begin
    if auth.uid() is null then
        raise exception 'يجب تسجيل الدخول';
    end if;

    v_price := public.zono_bird_price(p_item_id);
    v_new_rank := public.zono_bird_rank(p_item_id);
    v_daily := public.zono_bird_daily_seeds(p_item_id);

    if v_price is null or v_new_rank is null or v_new_rank <= 0 then
        raise exception 'هذا الطائر غير متاح للشراء';
    end if;

    select seeds, active_bird_rank
      into v_balance, v_current_rank
    from public.profiles
    where id = auth.uid()
    for update;

    -- يسمح بنفس المستوى مرة أخرى، لكن يمنع الرجوع إلى مستوى أقدم.
    if v_new_rank < coalesce(v_current_rank, 0) then
        raise exception 'لا يمكن شراء طائر أقدم من طائرك الحالي';
    end if;

    if coalesce(v_balance, 0) < v_price then
        raise exception 'رصيد البذور غير كافٍ';
    end if;

    update public.profiles
    set seeds = seeds - v_price,
        active_bird = case
            when v_new_rank >= coalesce(active_bird_rank, 0) then p_item_id
            else active_bird
        end,
        active_bird_rank = greatest(coalesce(active_bird_rank, 0), v_new_rank),
        bird_plan_started_at = now(),
        bird_plan_ends_at = now() + interval '500 days',
        bird_last_seed_claim = now()
    where id = auth.uid();

    -- يبقى inventory لتوافق الواجهة القديمة.
    insert into public.bird_inventory(user_id, item_id)
    values(auth.uid(), p_item_id)
    on conflict (user_id, item_id) do nothing;

    -- كل شراء يسجل كخطة إنتاج مستقلة لمدة 500 يوم.
    insert into public.bird_purchases(
        user_id, item_id, purchase_price, daily_seeds,
        purchased_at, ends_at, last_claim_at
    )
    values(
        auth.uid(), p_item_id, v_price, v_daily,
        now(), now() + interval '500 days', now()
    );

    select count(*)
      into v_count
    from public.bird_purchases
    where user_id = auth.uid()
      and item_id = p_item_id;

    select coalesce(sum(daily_seeds), 0)
      into v_total_daily
    from public.bird_purchases
    where user_id = auth.uid()
      and ends_at >= now();

    return jsonb_build_object(
        'ok', true,
        'item_id', p_item_id,
        'rank', v_new_rank,
        'price', v_price,
        'daily_seeds', v_daily,
        'duration_days', 500,
        'purchase_count', v_count,
        'total_daily_seeds', v_total_daily,
        'seeds', v_balance - v_price
    );
end;
$$;

-- جمع إنتاج جميع عمليات الشراء التي أكملت 24 ساعة.
create or replace function public.zono_claim_bird_daily_seeds()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_reward bigint := 0;
    v_claimed bigint := 0;
    v_balance bigint;
    v_total_daily bigint := 0;
begin
    if auth.uid() is null then
        raise exception 'يجب تسجيل الدخول';
    end if;

    with claimed as (
        update public.bird_purchases
        set last_claim_at = now()
        where user_id = auth.uid()
          and ends_at >= now()
          and last_claim_at <= now() - interval '24 hours'
        returning daily_seeds
    )
    select
        coalesce(sum(daily_seeds), 0)::bigint,
        count(*)::bigint
    into v_reward, v_claimed
    from claimed;

    if v_claimed = 0 or v_reward <= 0 then
        raise exception 'لم تكتمل 24 ساعة لأي طائر نشط بعد';
    end if;

    update public.profiles
    set seeds = seeds + v_reward,
        bird_last_seed_claim = now()
    where id = auth.uid()
    returning seeds into v_balance;

    select coalesce(sum(daily_seeds), 0)
      into v_total_daily
    from public.bird_purchases
    where user_id = auth.uid()
      and ends_at >= now();

    return jsonb_build_object(
        'ok', true,
        'reward', v_reward,
        'claimed_purchases', v_claimed,
        'seeds', v_balance,
        'total_daily_seeds', v_total_daily
    );
end;
$$;

grant execute on function public.zono_bird_purchase_counts() to authenticated;
grant execute on function public.zono_bird_daily_totals() to authenticated;
grant execute on function public.zono_buy_bird(text) to authenticated;
grant execute on function public.zono_claim_bird_daily_seeds() to authenticated;

commit;

notify pgrst, 'reload schema';

-- للاختبار فقط، يمكن منح حساب المطور بذوراً:
-- update public.profiles set seeds = 100000 where role = 'developer';
